In [1]:
# Getting parent directory of current direc and adding into the system path
import os, sys
parent_dir = os.path.dirname(os.getcwd())
sys.path.insert(0, parent_dir)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/home/am/Documents/Software Development/10_Academy Training/week2/Data/Copy of Week2_challenge_data_source(CSV).csv")

In [4]:
numeric_columns = df.select_dtypes(include=['float64', 'int64'])

In [5]:
# df.columns

In [6]:
from scripts.user_satisfaction_analysis import UserSatisfactionAnalyzer
user_satisfaction = UserSatisfactionAnalyzer(df)

In [7]:
normalized_data, kmeans, clusters = user_satisfaction.normalize_and_cluster(df)

In [8]:
clusters

array([1, 1, 1, ..., 1, 1, 1], dtype=int32)

In [9]:
engagement_scores = user_satisfaction.assign_engagement_score()

In [10]:
engagement_scores

MSISDN/Number  engagement_score
0        3.360100e+10          0.000461
1        3.360100e+10          0.001162
2        3.360100e+10          0.000154
3        3.360101e+10          0.001279
4        3.360101e+10          0.002001
...               ...               ...
106852   3.379000e+10          0.000378
106853   4.188282e+10          1.730326
106854   3.197021e+12          0.010256
106855   3.370000e+14          0.001622
106856   8.823971e+14          0.010168

[106857 rows x 2 columns]

In [11]:
experience_score = user_satisfaction.assign_experience_score()

In [12]:
experience_score

MSISDN/Number  experience_score
0        3.360100e+10          0.058493
1        3.360100e+10          0.076639
2        3.360100e+10          0.328630
3        3.360101e+10          0.386351
4        3.360101e+10          0.139133
...               ...               ...
106852   3.379000e+10          0.059662
106853   4.188282e+10          0.347985
106854   3.197021e+12          0.328804
106855   3.370000e+14          0.503890
106856   8.823971e+14          1.052662

[106857 rows x 2 columns]

In [13]:
merged_data, satisfaction_df, top10_customers = user_satisfaction.analyze_user_satisfaction()

In [14]:
top10_customers

MSISDN/Number  engagement_score  experience_score  satisfaction_score
106853   4.188282e+10          1.730326          0.347985            1.039156
44404    3.366149e+10          0.000831          1.310372            0.655601
95390    3.376155e+10          0.001642          1.278100            0.639871
72685    3.366966e+10          0.000720          1.241955            0.621338
79445    3.368206e+10          0.000868          1.235210            0.618039
5717     3.361378e+10          0.001565          1.220970            0.611268
58501    3.366504e+10          0.001717          1.214605            0.608161
83842    3.369565e+10          0.001285          1.210420            0.605853
23986    3.365025e+10          0.000684          1.207604            0.604144
96024    3.376170e+10          0.000820          1.207463            0.604141

In [15]:
model_regression = user_satisfaction.train_regression_model()

Regression Model Coefficients: [[ 1.00000000e+00  4.53608409e-05 -9.89427108e-06  1.77332849e-05]
 [ 8.67181669e-18  8.33333333e-01 -1.66666667e-01  3.33333333e-01]
 [ 8.00653865e-16 -1.66666667e-01  8.33333333e-01  3.33333333e-01]
 [ 4.04662841e-16  3.33333333e-01  3.33333333e-01  3.33333333e-01]]
Regression Model Intercept: [-2.28881836e-05 -4.16030371e-07 -3.84113660e-05 -1.94136982e-05]


In [16]:
cluster_df = user_satisfaction.kmeans_clustering()

/home/am/Documents/Software Development/10_Academy Training/week2/tellCo-business-analytics/venv-tellCo/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [17]:
cluster_df

cluster  satisfaction_score  experience_score
0        0            0.303461          0.605387
1        1            0.099132          0.196797